name: opd_creative_studio
description: A dedicated mobile reporting app for doctors using digital marketing services.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  fl_chart: ^0.65.0
  provider: ^6.1.1
  http: ^1.1.0
  shared_preferences: ^2.2.2
  shared_preferences_web: ^2.2.1
  cached_network_image: ^3.3.0
  cached_network_image_web: ^1.1.0
  flutter_staggered_animations: ^1.1.1
  shimmer: ^3.0.0
  flutter_web_plugins:
    sdk: flutter
  flutter_cache_manager: ^3.3.1
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  path_provider_web: ^2.2.1
  path: ^1.9.0
  sqflite_common_ffi_web: ^0.4.0+2
  sqflite_common_ffi: ^2.3.0
  ffi: ^2.1.0
  flutter_keyboard_visibility: ^6.0.0
  flutter_keyboard_visibility_web: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
